name: database
description: A new Flutter package project.
version: 1.2.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: 1.8.1
  path_provider: 2.0.11
  sqflite: 2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
